apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: 3-tier-app-eks
type: Opaque
data:
  DB_USERNAME: d2Vnb2FnYWlu
  DB_PASSWORD: d2Vnb2FnYWlu
  SECRET_KEY: ZGV2LXNlY3JldC1rZXk=
  DATABASE_URL: cG9zdGdyZXNxbDovL3dlZ29hZ2Fpbjp3ZWdvYWdhaW5AcG9zdGdyZXMtZGIuMy10aWVyLWFwcC1la3Muc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9wb3N0Z3Jlcw==
